#!/bin/sh

if [ -n "$STY" ]; then
  # If $STY set, we're in a screen; print to stderr
  echo "WARNING: You are inside a screen" 1>&2
fi

if [ -z "$1" ] || [ "$1" = "-l" ]; then
  # List running screens
  screen -ls
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  # Print some text
  echo "$0 [-l]   List running screens"
  echo "$0 -h     Print this help"
  echo "$0 NAME   Open a screen (^A D to detach from it)"
else
  # Reattach a session; detach first if necessary
  screen -d -r $1
fi
